# Generated by Django 3.2 on 2024-03-07 16:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='followed',
            new_name='followed_id',
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('owner', 'followed_id')},
        ),
    ]
