# Generated by Django 3.2.23 on 2024-03-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='availability',
        ),
    ]
