# Generated by Django 3.2 on 2024-03-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='year_created',
            field=models.PositiveIntegerField(),
        ),
    ]
