# Generated by Django 3.2.23 on 2024-03-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_alter_painting_year_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='year_created',
            field=models.DateField(),
        ),
    ]
